version: '3.5'

services:
  postgres:
    image: postgres:13
    container_name: 'postgres'
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/postgres-values.env
    networks:
      - dataspaceconnector
    volumes:
      - dataspaceconnector-data:/var/lib/postgresql/data

  connector:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:latest
    container_name: 'dataspaceconnector'
    ports:
      - 8080:8080
    env_file:
      - ./dataspaceconnector/dataspaceconnector-values.env
    networks:
      - dataspaceconnector
    volumes:
      - ./dataspaceconnector/config:/config
    depends_on:
      - postgres

networks:
  dataspaceconnector:

volumes:
  dataspaceconnector-data: {}
